spring.application.name=pharmasave

spring.datasource.url=jdbc:postgresql://localhost:5432/pharmasave
spring.datasource.username=postgres
spring.datasource.password=rishikareddy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
logging.level.org.springframework.security=DEBUG